### ISSUE TITLE
Camera testing process

### ISSUE THREAD

**Issue by idvoretskyi** [t3mujin/t3mujinpack#17]
A few cameras are listed here https://github.com/t3mujin/t3mujinpack#tested-cameras.

I'm an owner of Fuji X-T3 and X100F, and happy to test these presets with my cameras as well.

What is the process of testing them out?

**Comment by t3mujin** [comment]
Hi @idvoretskyi! Sorry for this really late reply, when you sent this I was totally under the water and this has been forgotten since. Also because the release of Darktable 3.0.0 broke my ability to update presets and for a couple of months I've put them aside, only now that 3.0.1 came out I'm returning to them and preparing a new version. 

...And checking the current issues :)

There's no formal testing process, the presets aren't meant to handle specific camera issues and should work with any. So that list is more to identify cameras that have been using the presets successfully. If you've been using the presets with those cameras without any issues let me know if I can add them to the list (I now own a X-T3 so I'm going to add it nevertheless).  But actually you gave me an idea: start asking ask users what cameras they're using.

**Comment by idvoretskyi** [comment]
@t3mujin all good, thanks for clarifying!
