### ISSUE TITLE
Olympus PEN E-PL5 RAW Sample

### ISSUE THREAD

**Issue by lostwanderingdrifter** [t3mujin/t3mujinpack#3]
Sending you a sample RAW file for Olympus E-PL5. I hope it helps you expand your test samples for your awesome work. I'm not sure if this is optimal, please let me know if you need other kinds of shots.

[P1031048.ORF.zip](https://github.com/t3mujin/t3mujinpack/files/872191/P1031048.ORF.zip)

**Comment by t3mujin** [comment]
I'll include this ion my test samples, and let you know if I more samples will be more helpful.
Thanks!

**Comment by mmrezaie** [comment]
Do you want to have e-m1 II samples?

**Comment by t3mujin** [comment]
Not really

*João Almeida*

about.me/ioaoalmeida

joaoalmeidaphotography.com

**Comment by mmrezaie** [comment]
Anything works? I have 12-40 mm f2.8 lens. I can share different scenarios of light and ISO values. I am not sure what exactly is the process and that's why I am asking.

And thank you very much for doing this. Yes I have always used your styles when I had the x-t2.

**Comment by t3mujin** [comment]
> Anything works?
Basically, yes! Just some really world samples, images you're likely to apply the presets or when the presets may be a bit off, and I've had cases of that: people sending me sample images in cases where the presets are a bit off, and that usually is because my sample images don't cover those colors/palette.
