### ISSUE TITLE
Big difference for Portra 400 between 0.3 and 0.4

### ISSUE THREAD

**Issue by risbac** [t3mujin/t3mujinpack#6]
Hello ! 

I'm testing the new 0.4 versions, and there is a big difference at least on the Portra 400VC that I'm using very very often. The new version is really much more saturated. I have uploaded three different versions  of the same photos with 0.3, 0.4 and no style applied : https://www.flickr.com/photos/smooth-bokeh/ (see at the top).

I was often adding some saturation to my Portra photos, so I guess maybe I'm biased and too used to the 0.3 version and not to the real film. But I thought it could be useful to let you know my feeling about it, as it's a big change and it's kinda my default film style. 

Thanks for the new version in any case, I'll be happy to test all the other ones slowly. 

best regards, 

    François

**Comment by t3mujin** [comment]
Hi François, I think I should've been more clear on the blog/release with the portras, I've done a lot of work on them. You telling me you had to add saturation kind of tells me you felt the same, I was missing the richer colors, every time I used it I felt it had to correct it every time. Your v0.4 sample has your saturation corrections?

**Comment by risbac** [comment]
Hi João

My v0.4 sample has zero saturation correction, just like my v0.3 sample was
also just with your style applied. The gamut alert on Darktable is also
saying that the v0.4 version is really pushing the colors. It feels a bit
like going from one extreme to the other one. I need to test on more
screens, but it really feels like I will have to desaturate a bit to avoid
too flashy colors. I really don't mean to sound like criticizing, I use
your themes a LOT (basically on every wedding set for instance), so I
wanted to share my feelings. I had already downloaded the v0.4 version when
it was a work in progress, and it gave me the same feeling : the colors
were too vivid, so I thought you would tame them a bit when finalizing. But
again, I'm not familiar with the film itself, so my reference is just the
v0.3 and my eyes :)

**Comment by risbac** [comment]
Maybe I'm doing something wrong, or I have a wrong setting in my Darktable ? Not to rely only on my eye and my use of your style (since I don't know the film), I have use two photos with the same settings : my default "flat" style in Darktable, then your V0.4, then from the "flat" jpg, I have used 2 different Portra 400VC simulation : the gmic Gimp plugin, and the online 29a.ch tool. Both gives a pretty similar result, so I guess they must be fine. Then the v0.4 version is too saturated, and with a red tint apparently. Even the 0.3 version seems too red. 

I'm trying to attach the two series of photos here : 

![20160424_114757_dsc02582_flat](https://user-images.githubusercontent.com/8427678/43611188-a353ce48-96a8-11e8-8523-1ae5e5eed6bb.jpg)
![20160424_114757_dsc02582_portra_400vc_29a ch](https://user-images.githubusercontent.com/8427678/43611189-a36c8640-96a8-11e8-9044-d0c1a50a8cd6.png)
![20160424_114757_dsc02582_portra_400vc_gmic](https://user-images.githubusercontent.com/8427678/43611190-a383c508-96a8-11e8-9625-9bde7ed92025.jpg)
![20160424_114757_dsc02582_portra_400vc_v0 4](https://user-images.githubusercontent.com/8427678/43611191-a39a0b7e-96a8-11e8-873d-3c792e5f8e50.jpg)
![28821870727_23c76c9c5c_o](https://user-images.githubusercontent.com/8427678/43611193-a3b70c56-96a8-11e8-90de-67f762a56835.jpg)
![28821870727_23c76c9c5c_o_gmic_portra400vc](https://user-images.githubusercontent.com/8427678/43611194-a3d28558-96a8-11e8-8d90-47eb1f00794d.jpg)
![28821870727_23c76c9c5c_o_gmic_portra400vc_29a ch](https://user-images.githubusercontent.com/8427678/43611195-a3eaa2c8-96a8-11e8-9cc6-44ab2a74a1e7.png)
![28821870727_23c76c9c5c_o_portra400vc_0 3](https://user-images.githubusercontent.com/8427678/43611196-a406492e-96a8-11e8-8b93-456b318140d2.jpg)
![28821870727_23c76c9c5c_o_portra400vc_0 4](https://user-images.githubusercontent.com/8427678/43611198-a433f9c8-96a8-11e8-9258-1cd8e89919cf.jpg)

**Comment by risbac** [comment]
Shit, the image names are changed. So in the right order : 
Flat Jpg / GMIC / 29a.ch / V0.4

then second photo : 
Flat Jpg / GMIC / 29a.ch / V0.3 / V0.4

**Comment by t3mujin** [comment]
Thanks François, I'll check with your images (and add them to my pool of test samples). I think I haven't tested the Portra VC/NC/UC with enough sample images, maybe I should explore darktable-cli to try to automate that.

**Comment by risbac** [comment]
Hello !

Just did with the Portra 400VC and I don't see any difference. Or it's
incredibly subtle. I compared the two tones curves in the lab, and I can't
see any visual difference on the curves, are you sure you commited the
right file ? Or my Darktable has a problem maybe ? I will test again on my
main computer tonight.

**Comment by t3mujin** [comment]
Have you checked if the style is turned on? Sometimes I save it with the curves set but the modules disabled.

**Comment by risbac** [comment]
yes I did. I duplicated the same photo I used for my comparion, I deleted
any editing, applied your style and used the snapshot option to compare it
with v0.4. I see virtually no difference. I'm wondering if your 400 UC is
not what the VC should be. UC is REALLY very saturated. VC is more
saturated than NC, but still not that saturated. I need to compare more on
my main computer, sometimes I'm wondering which version I'm really using,
it's easy to mix them if I don't name them with the version number in the
photo tag.

**Comment by t3mujin** [comment]
I wonder if you mixed some of your files, because I just downloaded the current ones styles from github and the release ones and the results are clearly different. Did you download them directly from github? I haven't released any new version yet.

 current 400NC / 0,4,0 400NC /  current 400UC / 0,4,0 400UC /  current 400VC / 0,4,0 400VC 

![43611188-a353ce48-96a8-11e8-8523-1ae5e5eed6bb](https://user-images.githubusercontent.com/331767/43719018-69b9e396-9984-11e8-945c-7870dec775da.jpg)
![43611188-a353ce48-96a8-11e8-8523-1ae5e5eed6bb_01](https://user-images.githubusercontent.com/331767/43719026-6dc35d6e-9984-11e8-8f77-d27f130e3106.jpg)
![43611188-a353ce48-96a8-11e8-8523-1ae5e5eed6bb_02](https://user-images.githubusercontent.com/331767/43719028-70725d6c-9984-11e8-8cca-d16161fa6a42.jpg)
![43611188-a353ce48-96a8-11e8-8523-1ae5e5eed6bb_03](https://user-images.githubusercontent.com/331767/43719032-721815e4-9984-11e8-9e13-1bf9f0033028.jpg)
![43611188-a353ce48-96a8-11e8-8523-1ae5e5eed6bb_04](https://user-images.githubusercontent.com/331767/43719035-73d6d528-9984-11e8-850e-ef24c8115eab.jpg)
![43611188-a353ce48-96a8-11e8-8523-1ae5e5eed6bb_05](https://user-images.githubusercontent.com/331767/43719041-75f6bf6c-9984-11e8-8c1a-c5920e86128a.jpg)

![43611193-a3b70c56-96a8-11e8-90de-67f762a56835](https://user-images.githubusercontent.com/331767/43719050-7ad5ad86-9984-11e8-97a3-db8b43ca8e9a.jpg)
![43611193-a3b70c56-96a8-11e8-90de-67f762a56835_01](https://user-images.githubusercontent.com/331767/43719054-7c382014-9984-11e8-8238-17e5a8373014.jpg)
![43611193-a3b70c56-96a8-11e8-90de-67f762a56835_02](https://user-images.githubusercontent.com/331767/43719058-7e2fa220-9984-11e8-9f53-e7970c6843d5.jpg)
![43611193-a3b70c56-96a8-11e8-90de-67f762a56835_03](https://user-images.githubusercontent.com/331767/43719061-7fa03b92-9984-11e8-9ad6-96c1db521650.jpg)
![43611193-a3b70c56-96a8-11e8-90de-67f762a56835_04](https://user-images.githubusercontent.com/331767/43719063-80fe78dc-9984-11e8-92be-290f1f76ee12.jpg)
![43611193-a3b70c56-96a8-11e8-90de-67f762a56835_05](https://user-images.githubusercontent.com/331767/43719065-82f36ec2-9984-11e8-8492-b390b6c6c46d.jpg)

**Comment by risbac** [comment]
indeed, your files look much better ! I must be mixing something. Or
lacking coffee. Or maybe both. It's bloody hot these days here, my brain
must lack some oxygen. I can't imagine how it must be in Portugal ;)

I will test again tonight with more time. Sorry for the failed test.

**Comment by t3mujin** [comment]
Ahahahahah! I can relate to that.

Those aren't the final versions of the styles yet, just a work in progress, I'll need to do some further testing with a broader ser of image samples, and then release a 0.4.1, with these fixes .

**Comment by risbac** [comment]
it looks very promising in any case. I will make sure to do better tests
tonight. Keep up the good work !
